name: Update Website

on:
  push:
    branches:
      - main

  workflow_dispatch:


jobs:
  run-notebook:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install jupyter nbconvert

    - name: Run Jupyter Notebook
      run: |
        jupyter nbconvert --to python create_html.ipynb
        python3 create_html.py

    - name: Commit and push changes
      run: |
        git config user.name 'github-actions[bot]'
        git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
        git add .
        git commit --allow-empty -m "Pushed from website generator"
        git push
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}